import { PDFDocument, StandardFonts, rgb } from "pdf-lib";
import type { InvoiceView } from "../modules/invoices/service.js";

const MARGIN = 50;
const PAGE_WIDTH = 595.28; // A4

function truncate(text: string, max: number): string {
  return text.length > max ? `${text.slice(0, max - 1)}…` : text;
}

// US-INVOICE-03 — render an invoice as a downloadable PDF. The document mirrors
// exactly the line items, total, due date, and status shown in the app.
export async function generateInvoicePdf(view: InvoiceView): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const page = doc.addPage([PAGE_WIDTH, 841.89]);
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  const { height } = page.getSize();
  let y = height - MARGIN;

  const line = (text: string, size = 11, useBold = false, gap = 16): void => {
    page.drawText(text, {
      x: MARGIN,
      y,
      size,
      font: useBold ? bold : font,
      color: rgb(0, 0, 0),
    });
    y -= gap;
  };

  line("RosiHome Invoice", 22, true, 30);
  line(`Invoice ID: ${view.id}`);
  line(`Billing Period: ${view.billingPeriod}`);
  line(`Status: ${view.status}`);
  line(`Issue Date: ${view.issueDate}`);
  line(`Due Date: ${view.dueDate}`);
  y -= 8;
  line("Line Items", 14, true, 22);

  for (const item of view.lineItems) {
    const label = truncate(`${item.description}`, 52);
    const amount = `${(item.amount ?? 0).toLocaleString("en-US")} VND`;
    line(`${label.padEnd(54)}${amount}`, 11);
  }

  y -= 8;
  line(`Total: ${view.totalAmount.toLocaleString("en-US")} VND`, 14, true, 24);
  line("Generated by RosiHome.", 9, false, 12);

  return doc.save();
}
