import { PDFDocument, StandardFonts, rgb } from "pdf-lib";

const MARGIN = 50;
const PAGE_WIDTH = 595.28; // A4

function truncate(text: string, max: number): string {
  return text.length > max ? `${text.slice(0, max - 1)}…` : text;
}

function formatCurrency(amount: number | string | undefined): string {
  if (amount === "N/A" || amount === undefined) return "N/A";
  return `${Number(amount).toLocaleString("en-US")} VND`;
}

// US-REPORT-05 — render a business report as a downloadable PDF.
export async function generateReportPdf(snapshot: any): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  let page = doc.addPage([PAGE_WIDTH, 841.89]);
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);

  let { height } = page.getSize();
  let y = height - MARGIN;

  const checkPageBreak = (neededGap: number) => {
    if (y - neededGap < MARGIN) {
      page = doc.addPage([PAGE_WIDTH, 841.89]);
      y = height - MARGIN;
    }
  };

  const line = (text: string, size = 11, useBold = false, gap = 16, indent = 0): void => {
    checkPageBreak(gap);
    page.drawText(text, {
      x: MARGIN + indent,
      y,
      size,
      font: useBold ? bold : font,
      color: rgb(0, 0, 0),
    });
    y -= gap;
  };

  line("RosiHome Business Report", 22, true, 30);
  line(`Report ID: ${snapshot.reportId}`);
  
  if (snapshot.period.type === "month") {
    line(`Period: ${snapshot.period.month}`);
  } else {
    line(`Period: ${snapshot.period.startDate} to ${snapshot.period.endDate}`);
  }
  
  const tz = snapshot.timezone || "UTC";
  line(`Generated At: ${new Date(snapshot.generatedAt).toLocaleString("en-US", { timeZone: tz })}`);
  line(`Landlord ID: ${snapshot.landlordId}`);
  
  y -= 10;
  
  // === Financial Summary ===
  line("1. Financial Summary", 16, true, 22);
  
  const fin = snapshot.financial;
  line("Expected Revenue", 12, true, 16, 10);
  line(`Rent: ${formatCurrency(fin.expectedRevenue.rent)}`, 11, false, 14, 20);
  line(`Electricity: ${formatCurrency(fin.expectedRevenue.electricity)}`, 11, false, 14, 20);
  line(`Water: ${formatCurrency(fin.expectedRevenue.water)}`, 11, false, 14, 20);
  line(`Surcharges: ${formatCurrency(fin.expectedRevenue.surcharges)}`, 11, false, 14, 20);
  
  y -= 6;
  line("Actual Collected Revenue", 12, true, 16, 10);
  line(`Rent: ${formatCurrency(fin.actualCollectedRevenue.rent)}`, 11, false, 14, 20);
  line(`Electricity: ${formatCurrency(fin.actualCollectedRevenue.electricity)}`, 11, false, 14, 20);
  line(`Water: ${formatCurrency(fin.actualCollectedRevenue.water)}`, 11, false, 14, 20);
  line(`Surcharges: ${formatCurrency(fin.actualCollectedRevenue.surcharges)}`, 11, false, 14, 20);
  
  y -= 6;
  line(`Total Outstanding Debt: ${formatCurrency(fin.totalOutstandingDebt)}`, 12, true, 20, 10);
  
  if (fin.overdueInvoices && fin.overdueInvoices.length > 0) {
    line("Overdue Invoices:", 11, true, 16, 10);
    for (const inv of fin.overdueInvoices) {
      line(`- ${truncate(inv.tenant, 20)} (${inv.room}): ${formatCurrency(inv.amount)} due ${inv.dueDate}`, 10, false, 14, 20);
    }
  } else {
    line("Overdue Invoices: None", 11, false, 16, 10);
  }
  
  y -= 10;
  
  // === Occupancy & Churn ===
  line("2. Occupancy & Churn", 16, true, 22);
  const occ = snapshot.occupancy;
  line(`Average Occupancy Rate: ${occ.averageOccupancyRate !== "N/A" ? occ.averageOccupancyRate + "%" : "N/A"}`, 12, false, 16, 10);
  line(`Move-ins: ${occ.moveIns}`, 12, false, 16, 10);
  line(`Move-outs: ${occ.moveOuts}`, 12, false, 16, 10);
  
  if (occ.upcomingExpirations && occ.upcomingExpirations.length > 0) {
    line("Upcoming Expirations:", 11, true, 16, 10);
    for (const exp of occ.upcomingExpirations) {
      line(`- ${truncate(exp.tenant, 20)} (${exp.room}): Ends ${exp.endDate}`, 10, false, 14, 20);
    }
  } else {
    line("Upcoming Expirations: None", 11, false, 16, 10);
  }

  y -= 10;
  
  // === Maintenance Efficiency ===
  line("3. Maintenance Efficiency", 16, true, 22);
  const maint = snapshot.maintenance;
  line(`New Requests: ${maint.newRequests}`, 12, false, 16, 10);
  line(`Completed Requests: ${maint.completedRequests}`, 12, false, 16, 10);
  line(`Resolution Rate: ${maint.resolutionRate !== "N/A" ? maint.resolutionRate + "%" : "N/A"}`, 12, false, 16, 10);
  line(`Average Resolution Time: ${maint.averageResolutionTime !== "N/A" ? maint.averageResolutionTime + " hours" : "N/A"}`, 12, false, 16, 10);

  y -= 10;
  line("Generated by RosiHome.", 9, false, 12);

  return doc.save();
}
