import { useEffect,useState } from 'react'; import { Alert,Pressable,ScrollView,StyleSheet,Text,View } from 'react-native'; import { router,useLocalSearchParams } from 'expo-router'; import { SafeAreaView } from 'react-native-safe-area-context'; import { Badge,Button,Card,EmptyState,Feedback,Field,Screen,Success,Title,colors,spacing } from '@/ui'; import { useMockData,vnd } from '@/features/mock-data';
export function PropertiesListScreen(){const {properties,rooms}=useMockData();const [loading,setLoading]=useState(true);const [empty,setEmpty]=useState(false);const [error,setError]=useState(false);useEffect(()=>{const t=setTimeout(()=>setLoading(false),500);return()=>clearTimeout(t)},[]);if(loading)return <Screen><Feedback type="loading"/></Screen>;if(error)return <Screen><Feedback type="error" message="Không thể tải danh sách bất động sản" onRetry={()=>setError(false)}/></Screen>;return <Screen><Title subtitle="Quản lý phòng và chi phí theo từng địa chỉ.">Bất động sản</Title><View style={s.actions}><Button label="Thêm bất động sản" onPress={()=>router.push('/property-form')}/><Button label={empty?'Hiện dữ liệu':'Xem empty state'} variant="secondary" onPress={()=>setEmpty(x=>!x)}/><Button label="Xem error state" variant="secondary" onPress={()=>setError(true)}/></View>{empty?<EmptyState title="Chưa có bất động sản" description="Thêm nhà trọ đầu tiên để bắt đầu." action={<Button label="Thêm ngay" onPress={()=>router.push('/property-form')}/>}/>:properties.map(p=><Card key={p.id} onPress={()=>router.push({pathname:'/property-detail',params:{id:p.id}})}><Text style={s.cardTitle}>{p.name}</Text><Text style={s.muted}>{p.address}</Text><Text style={s.meta}>{rooms.filter(r=>r.propertyId===p.id).length} phòng</Text></Card>)}</Screen>}
export function PropertyFormScreen(){const {addProperty}=useMockData();const [name,setName]=useState('');const [address,setAddress]=useState('');const [done,setDone]=useState(false);return <Screen><Title subtitle="Thông tin dùng để phân nhóm phòng và chi phí.">Thêm bất động sản</Title>{done&&<Success message="Đã lưu bất động sản"/>}<Field label="Tên bất động sản *" value={name} onChangeText={setName} error={!name?'Không được để trống':undefined}/><Field label="Địa chỉ *" value={address} onChangeText={setAddress}/><Button label="Lưu và thêm phòng" disabled={!name||!address} onPress={()=>{addProperty({name,address});setDone(true);setTimeout(()=>router.replace('/room-form'),400)}}/></Screen>}
type PropertyTab='rooms'|'utilities'|'surcharges';
type RoomFilter='all'|'vacant'|'occupied';
export function PropertyDetailScreen(){
  const {id='p1'}=useLocalSearchParams<{id?:string}>();
  const {properties,rooms,surcharges,toggleSurcharge}=useMockData();
  const [tab,setTab]=useState<PropertyTab>('rooms');
  const [roomFilter,setRoomFilter]=useState<RoomFilter>('all');
  const property=properties.find(x=>x.id===id)??properties[0];
  const propertyRooms=rooms.filter(x=>x.propertyId===property?.id);
  const vacantCount=propertyRooms.filter(x=>x.status==='Trống').length;
  const occupiedCount=propertyRooms.filter(x=>x.status==='Đang thuê').length;
  const filteredRooms=propertyRooms.filter(room=>roomFilter==='all'||(roomFilter==='vacant'&&room.status==='Trống')||(roomFilter==='occupied'&&room.status==='Đang thuê'));
  const propertySurcharges=surcharges.filter(x=>x.propertyId===property?.id);
  const stop=(surchargeId:string)=>Alert.alert('Ngừng áp dụng phụ phí?','Dữ liệu cũ vẫn được giữ lại.',[{text:'Hủy',style:'cancel'},{text:'Ngừng áp dụng',style:'destructive',onPress:()=>toggleSurcharge(surchargeId)}]);
  const roomFilters=[{key:'all',label:`Tất cả · ${propertyRooms.length}`},{key:'vacant',label:`Trống · ${vacantCount}`},{key:'occupied',label:`Đang thuê · ${occupiedCount}`}] as const;
  return <SafeAreaView style={s.detailSafe}>
    <View style={s.detailHeader}>
      <View style={s.headerRow}><Pressable accessibilityLabel="Quay lại" hitSlop={8} style={s.headerAction} onPress={()=>router.back()}><Text style={s.backIcon}>‹</Text></Pressable><Text numberOfLines={1} style={s.detailTitle}>{property?.name??'Bất động sản'}</Text><Pressable style={s.headerAction} onPress={()=>router.push('/property-form')}><Text style={s.editText}>Sửa</Text></Pressable></View>
      <Text numberOfLines={2} style={s.detailAddress}>{property?.address}</Text>
      <View style={s.segment}>{([{key:'rooms',label:'Phòng'},{key:'utilities',label:'Điện nước'},{key:'surcharges',label:'Phụ phí'}] as const).map(item=><Pressable key={item.key} style={[s.segmentItem,tab===item.key&&s.segmentItemActive]} onPress={()=>setTab(item.key)}><Text style={[s.segmentText,tab===item.key&&s.segmentTextActive]}>{item.label}</Text></Pressable>)}</View>
      {tab==='rooms'&&<View style={[s.segment,s.roomFilter]}>{roomFilters.map(item=><Pressable key={item.key} style={[s.segmentItem,roomFilter===item.key&&s.segmentItemActive]} onPress={()=>setRoomFilter(item.key)}><Text style={[s.segmentText,roomFilter===item.key&&s.segmentTextActive]}>{item.label}</Text></Pressable>)}</View>}
    </View>
    <ScrollView contentContainerStyle={s.detailContent}>
      {tab==='rooms'&&<><View style={s.actions}><Button label="Thêm phòng" onPress={()=>router.push('/room-form')}/><Button label="Tạo nhiều phòng" variant="secondary" onPress={()=>router.push('/bulk-rooms')}/></View>{filteredRooms.length===0?<EmptyState title="Không có phòng phù hợp" description="Thử chọn bộ lọc khác hoặc thêm phòng mới."/>:filteredRooms.map(room=><Card key={room.id}><View style={s.row}><View><Text style={s.cardTitle}>Phòng {room.name}</Text><Text style={s.muted}>{vnd(room.rent)} / tháng</Text></View><Badge label={room.status}/></View></Card>)}</>}
      {tab==='utilities'&&<><Card><Text style={s.cardTitle}>Giá điện</Text><Text style={s.rateValue}>3.500 đ / kWh</Text><Text style={s.muted}>Áp dụng từ 01/08/2026</Text></Card><Card><Text style={s.cardTitle}>Giá nước</Text><Text style={s.rateValue}>18.000 đ / m³</Text><Text style={s.muted}>Tính theo đồng hồ</Text></Card><Button label="Chỉnh sửa giá điện nước" onPress={()=>router.push('/utility-rates')}/></>}
      {tab==='surcharges'&&<><Button label="Thêm phụ phí" onPress={()=>router.push('/surcharge-form')}/>{propertySurcharges.length===0?<EmptyState title="Chưa có phụ phí" description="Thêm Internet, vệ sinh hoặc chi phí định kỳ khác."/>:propertySurcharges.map(item=><Card key={item.id}><View style={s.row}><View><Text style={s.cardTitle}>{item.name}</Text><Text style={s.muted}>{vnd(item.amount)} / tháng</Text></View><Badge label={item.status}/></View><Button label={item.status==='Đang áp dụng'?'Ngừng áp dụng':'Áp dụng lại'} variant="secondary" onPress={()=>item.status==='Đang áp dụng'?stop(item.id):toggleSurcharge(item.id)}/></Card>)}</>}
    </ScrollView>
  </SafeAreaView>
}
export function RoomsListScreen(){const {rooms}=useMockData();const [empty,setEmpty]=useState(false);return <Screen><Title subtitle="Trạng thái thuê được cập nhật bằng mock state.">Danh sách phòng</Title><View style={s.actions}><Button label="Thêm phòng" onPress={()=>router.push('/room-form')}/><Button label="Tạo nhiều" variant="secondary" onPress={()=>router.push('/bulk-rooms')}/><Button label={empty?'Hiện dữ liệu':'Empty state'} variant="secondary" onPress={()=>setEmpty(x=>!x)}/></View>{empty?<EmptyState title="Chưa có phòng" description="Thêm một phòng hoặc tạo nhiều phòng cùng lúc."/>:rooms.map(r=><Card key={r.id}><View style={s.row}><View><Text style={s.cardTitle}>Phòng {r.name}</Text><Text style={s.muted}>{vnd(r.rent)} / tháng</Text></View><Badge label={r.status}/></View></Card>)}</Screen>}
export function RoomFormScreen(){const {addRoom}=useMockData();const [name,setName]=useState('');const [rent,setRent]=useState('');const amount=Number(rent.replace(/\D/g,''));return <Screen><Title>Thêm phòng</Title><Field label="Tên / số phòng *" value={name} onChangeText={setName}/><Field label="Giá thuê *" value={rent} onChangeText={setRent} keyboardType="numeric" error={rent&&amount<0?'Số tiền không được âm':undefined}/><Field label="Diện tích" keyboardType="numeric"/><Button label="Lưu phòng" disabled={!name||!rent} onPress={()=>{addRoom({propertyId:'p1',name,rent:amount,area:20});router.back()}}/></Screen>}
export function BulkRoomFormScreen(){const {addRooms}=useMockData();const [prefix,setPrefix]=useState('P');const [start,setStart]=useState('101');const [count,setCount]=useState('6');const [rent,setRent]=useState('3500000');return <Screen><Title subtitle="Tối đa 50 phòng trong một lần.">Tạo nhiều phòng</Title><Field label="Tiền tố" value={prefix} onChangeText={setPrefix}/><Field label="Số bắt đầu" value={start} onChangeText={setStart} keyboardType="numeric"/><Field label="Số lượng" value={count} onChangeText={setCount} keyboardType="numeric"/><Field label="Giá thuê chung" value={rent} onChangeText={setRent} keyboardType="numeric"/><Button label={`Tạo ${count||0} phòng`} onPress={()=>{addRooms('p1',prefix,Number(start),Math.min(Number(count),50),Number(rent));router.back()}}/></Screen>}
const s=StyleSheet.create({actions:{gap:spacing.sm,marginBottom:spacing.sm},cardTitle:{fontSize:16,fontWeight:'800',color:colors.text},muted:{fontSize:14,color:colors.textSecondary},meta:{fontSize:12,color:colors.primary,fontWeight:'700'},row:{flexDirection:'row',justifyContent:'space-between',alignItems:'flex-start'},detailSafe:{flex:1,backgroundColor:colors.background},detailHeader:{paddingHorizontal:spacing.lg,paddingBottom:spacing.md,backgroundColor:colors.background},headerRow:{minHeight:52,flexDirection:'row',alignItems:'center',justifyContent:'space-between'},headerAction:{width:52,minHeight:44,alignItems:'flex-start',justifyContent:'center'},backIcon:{fontSize:34,lineHeight:36,color:colors.text},detailTitle:{flex:1,fontSize:24,fontWeight:'800',textAlign:'center',color:colors.text},editText:{fontSize:16,fontWeight:'700',color:colors.primary},detailAddress:{fontSize:14,color:colors.textSecondary,marginBottom:spacing.lg},detailContent:{padding:spacing.lg,paddingTop:spacing.md,paddingBottom:spacing.xxl,gap:spacing.md},segment:{flexDirection:'row',backgroundColor:colors.surfaceAlt,borderRadius:12,padding:4},roomFilter:{marginTop:spacing.sm},segmentItem:{flex:1,minHeight:44,alignItems:'center',justifyContent:'center',borderRadius:10},segmentItemActive:{backgroundColor:colors.surface,borderWidth:1,borderColor:colors.border},segmentText:{fontSize:13,fontWeight:'700',color:colors.textSecondary},segmentTextActive:{color:colors.text},rateValue:{fontSize:20,fontWeight:'800',color:colors.text}});
